#!/bin/bash

# The `pre-command` hook will run just before your build command runs

# Note that as the script is sourced not run directly, the shebang line will be ignored
# See https://buildkite.com/docs/agent/v3/hooks#creating-hook-scripts

set -e

HOOKS_ROOT=$( dirname "${BASH_SOURCE[0]}" )
PLUGIN_ROOT=$( dirname "$HOOKS_ROOT" )
PLUGIN_BIN="$PLUGIN_ROOT/bin"

export PATH="$PATH:$PLUGIN_BIN"

# set buildevent env vars to match our plugin attributes
if [ -n "$BUILDKITE_PLUGIN_BUILDEVENTS_DATASET" ]; then
  export BUILDEVENT_DATASET=$BUILDKITE_PLUGIN_BUILDEVENTS_DATASET
fi
if [ -n "$BUILDKITE_PLUGIN_BUILDEVENTS_APIHOST" ]; then
  export BUILDEVENT_APIHOST=$BUILDKITE_PLUGIN_BUILDEVENTS_APIHOST
fi

