@echo off
SETLOCAL

REM Check if BUILDKITE_TRIGGERED_FROM_BUILD_ID is set and not empty
IF NOT "%BUILDKITE_TRIGGERED_FROM_BUILD_ID%"=="" (
    SET "TRACE_ID=%BUILDKITE_TRIGGERED_FROM_BUILD_ID%"
) ELSE (
    SET "TRACE_ID=%BUILDKITE_BUILD_ID%"
)

REM Execute the buildevents command
echo buildevents step %TRACE_ID% %BUILDKITE_STEP_ID% %_BUILDEVENT_STEP_START_TIME% %BUILDKITE_STEP_KEY%
buildevents step %TRACE_ID% %BUILDKITE_STEP_ID% %_BUILDEVENT_STEP_START_TIME% %BUILDKITE_STEP_KEY%

ENDLOCAL
